export type Timezone = {
  value: string;
  label: string;
};

export const TIMEZONES: Timezone[] = [
  { value: "UTC", label: "UTC" },
  { value: "Europe/London", label: "London (GMT)" },
  { value: "Europe/Paris", label: "Paris (CET)" },
  { value: "Europe/Athens", label: "Athens (EET)" },
  { value: "Europe/Berlin", label: "Berlin (CET)" },
  { value: "Europe/Moscow", label: "Moscow (MSK)" },
  { value: "America/New_York", label: "Eastern Time (ET)" },
  { value: "America/Chicago", label: "Central Time (CT)" },
  { value: "America/Denver", label: "Mountain Time (MT)" },
  { value: "America/Los_Angeles", label: "Pacific Time (PT)" },
  { value: "America/Sao_Paulo", label: "São Paulo (BRT)" },
  { value: "Asia/Tokyo", label: "Tokyo (JST)" },
  { value: "Asia/Shanghai", label: "Shanghai (CST)" },
  { value: "Asia/Singapore", label: "Singapore (SGT)" },
  { value: "Asia/Kolkata", label: "India (IST)" },
  { value: "Asia/Dubai", label: "Dubai (GST)" },
  { value: "Australia/Sydney", label: "Sydney (AEST)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (SAST)" },
  { value: "Africa/Cairo", label: "Cairo (EET)" },
  { value: "Pacific/Auckland", label: "Auckland (NZST)" },
  { value: "America/Mexico_City", label: "Mexico City (CST)" },
  { value: "America/Vancouver", label: "Vancouver (PT)" },
  { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires (ART)" },
  { value: "Europe/Madrid", label: "Madrid (CET)" },
  { value: "Europe/Rome", label: "Rome (CET)" },
  { value: "Europe/Istanbul", label: "Istanbul (TRT)" },
  { value: "Asia/Seoul", label: "Seoul (KST)" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT)" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB)" },
  { value: "Asia/Manila", label: "Manila (PHT)" },
  { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (MYT)" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh City (ICT)" },
  { value: "Asia/Baghdad", label: "Baghdad (AST)" },
  { value: "Asia/Jerusalem", label: "Jerusalem (IST)" },
  { value: "Asia/Riyadh", label: "Riyadh (AST)" },
  { value: "Asia/Tehran", label: "Tehran (IRST)" },
  { value: "Asia/Karachi", label: "Karachi (PKT)" },
  { value: "Asia/Kathmandu", label: "Kathmandu (NPT)" },
  { value: "Asia/Colombo", label: "Colombo (IST)" },
  { value: "Asia/Dhaka", label: "Dhaka (BST)" },
  { value: "Asia/Yangon", label: "Yangon (MMT)" },
  { value: "Asia/Baku", label: "Baku (AZT)" },
  { value: "Asia/Tbilisi", label: "Tbilisi (GET)" },
  { value: "Asia/Almaty", label: "Almaty (ALMT)" },
  { value: "Asia/Vladivostok", label: "Vladivostok (VLAT)" },
  { value: "Pacific/Honolulu", label: "Honolulu (HST)" },
  { value: "Pacific/Fiji", label: "Fiji (FJT)" },
  { value: "Pacific/Tahiti", label: "Tahiti (TAHT)" },
  { value: "Pacific/Guam", label: "Guam (ChST)" },
  { value: "Pacific/Port_Moresby", label: "Port Moresby (PGT)" },
  { value: "Pacific/Samoa", label: "Samoa (SST)" },
  { value: "Atlantic/Azores", label: "Azores (AZOT)" },
  { value: "Atlantic/Cape_Verde", label: "Cape Verde (CVT)" },
  { value: "Africa/Lagos", label: "Lagos (WAT)" },
  { value: "Africa/Nairobi", label: "Nairobi (EAT)" },
  { value: "Africa/Accra", label: "Accra (GMT)" },
  { value: "Africa/Casablanca", label: "Casablanca (WET)" },
  { value: "Africa/Algiers", label: "Algiers (CET)" },
  { value: "Antarctica/Casey", label: "Casey (AWST)" },
  { value: "Antarctica/South_Pole", label: "South Pole (NZST)" },
];
